### ISSUE TITLE
error: no matching package named `differ` found

### ISSUE THREAD

**Issue by EDePasquale** [furlan-lab/mergebams#1]
Hi,

I am trying to compile mergebams and I am getting the following message after running `cargo build --release`:
```
    Updating crates.io index
error: no matching package named `differ` found
location searched: registry `crates-io`
required by package `mergebams v0.3.0 (/users/dep1kb/mergebams)`
```
I looked this error up and it seems like the 'differ' package is no longer available on crates.io [(https://crates.io/crates/differ)](url)

Thanks,
Erica

**Comment by scfurl** [comment]
Hi @EDePasquale.  Sorry this isn't working.  You are correct that the differ package is no longer available.  I have forked it and committed an updated Cargo.toml.  Hopefully it will work for you now!

**Comment by EDePasquale** [comment]
Yes, this works now. Thanks!
