### ISSUE TITLE
fail_bam query

### ISSUE THREAD

**Issue by sxf-ux** [furlan-lab/mergebams#2]
hi. thanks for such a great tool!

I had a question. what was the purpose of `fail_bam.bam` ? why is that an additional output alongside `out_bam.bam `?

thank you !

**Comment by scfurl** [comment]
Thanks for trying mergebams! @sxf-ux   The fail_bam.bam file has all the reads that for any number of reasons didn't have their cell barcode properly prepended.  In a way, it is a way of "keeping the train running".  Any read that may have some problem will get siphoned off into fail_bam allowing the whole process to keep going.  I don't think I have ever done anything but look at the file size of fail_bam and ensure it isn't more than a few kb.  I will add some language to the documentation so this is clear for others who have the same question
